### ISSUE TITLE
How to get the R_t  values?

### ISSUE THREAD

**Issue by Yorshh** [srivastavaprashant/mgarch#5]
Hi! I am trying to apply the DCC-GARCH(1,1) model for two financial time series with the intention of only get the dynamic correlation between those assets throught time, but im not sure if i am understanding the code at all ¿How could i get those values? as I understand it, I can achieve this by getting the R_t matrix, but I don't know how to get it, I would really appreciate your help!

Atte. 
A stressed student jajaja :(

**Comment by srivastavaprashant** [comment]
Navigate to mgarch class and edit the code to return R_t values. :)
